### ISSUE TITLE
KeyError: '9'

### ISSUE THREAD

**Issue by justingrayston** [googleartsculture/cluster-analysis#22]
Error found in main.py

```
Traceback (most recent call last):
  File "/srv/main.py", line 753, in cluster_analysis
    result = do_cluster_analysis(image,
  File "/srv/main.py", line 186, in do_cluster_analysis
    merge(job_dict, merge_dict, cartouche_list)
  File "/srv/main.py", line 455, in merge
    job_dict['clusters_processed'].pop(inner)
KeyError: '9'
```

**Comment by roybgardner** [comment]
@justingrayston Interesting. Does key `'9'` appear more than once in `pop_list`? A key can only get into `pop_list` if it exists in `job_dict['clusters_processed']` (assuming the code works), so a duplicate may explain this error.

**Comment by justingrayston** [comment]
Doesn't it just mean that `inner`, which in this case is '9' isn't in job_dict['clusters_processed']. There is no Key to pop. There are a few other examples with other number values. Feels like perhaps some iteration log expecting 9 to be there, but it never was or that it already has been popped. I guess that's what your getting at, two 9s in the list that creates inner and this would happen. 

I'll take a look through the logic.. Errors are few and far between atm.

**Comment by roybgardner** [comment]
Perhaps it's cartouche-related:  because cartouches are generated pre-merge, a cluster could be both inside a cartouche, and also inside another cluster in the cartouche.

**Comment by justingrayston** [comment]
PR #23 will catch the key error, but I am not convinced this should be happening in the first place. I've done the simple "fix" for now to stop 500 errors, but I'd like to be able to reproduce with an actual glyph image test, and so far I haven't managed to get it to do it.

**Comment by roybgardner** [comment]
The attached will test the cartouche hypothesis.

![cartouche_test_2](https://user-images.githubusercontent.com/11853656/89731474-29f5f080-da3f-11ea-87f7-505af611cdb1.png)
![cartouche_test](https://user-images.githubusercontent.com/11853656/89731475-2b271d80-da3f-11ea-8bc3-e68707ea64ef.png)

**Comment by justingrayston** [comment]
Thanks - I've been taking a bit of time off - just getting back into the swing of things. Will test this week.

**Comment by roybgardner** [comment]
Meant to say that I tested with these images but couldn't replicate the issue.
